$ANSIBLE_VAULT;1.1;AES256
34313937363536383964663636326362356366643362616564353131333735623139643236346662
3962343838633434313434313337356234383962336261630a646661323635313538613437383139
61353230663532376131666630336232623463646463363666636137326139393032363866616537
3730623163636463630a376164646461646331656533383337383265363630316333653732663362
38336135616238316563613061366363386565343133333935643532613132326637356137353964
35316265306466636330383538316361336133326461333238663463393365326465636535616665
37663033623538346531333530386465643063633836316163356662396534633664313134363336
61626431333364653065353535336362346363366532656661343235366231633966303331303234
35323762303736393766373463313861316336393464633036306332326235343332333764393636
35376237643332393037653336623738626563616566386335386165356239383634393866366264
64623864636565363334316133626364396361633936346330373664333338336130393330613461
63353638643139383535636465316139393439396261613565646138323836633534316536643231
62346561336166323837326431303433636331643263653031613033623466663863633162343465
32303537663332643263363165333363656137383837303234336433626232383831363463636234
66663134646631366334376239643531323831376632623337353232366661323938326362386536
31313138326561623865343633383533356165303930383732366437656130613938663431386432
30353266363533383161646466356464643439356531653533656439633738353234663539633533
3636653033343733383966333037613837396535633364336130
